version: '3.8'

services:
  app:
    build: .
    container_name: nft_frontend
    ports:
      - "3000:3000"
    working_dir: "/src"
    volumes:
      - "./src:/src"
      - node_modules_volume:/src/node_modules
    tty: true
    environment:
    - CHOKIDAR_USEPOLLING=true
volumes:
  node_modules_volume: